### PR TITLE
Fix(be) mentor registration

### LINKED ISSUE #66: (BE) Mentor Registration Form
**Description:** As a system, I want to create a new Mentor accounts. So that Mentor will be authenticated and can access the platform

**Background:** Given the Mentor Registration endpoint is available

**Scenario:** Successful registration with valid data
When the Mentor enters a valid Full Name (text)
And the Mentor enters a valid Email Address (unique, valid format)
And enters a valid Phone number
And enters a valid Password (min 8 chars, must include uppercase + number + special character)
And enters a valid Confirm Password (must match)
And selects a valid Country
And selects a valid Timezone
And can optionally select Preferred Language (with default English)
And can select multiple Areas of expertise (must select at least one)
And enters Years of experience
And enters LinkedIn Profile URL (optional)
And Uploads verification documents (accepts pdf & image format only, max. 10MB)
And checks the Accept Terms & Conditions (checkbox)
Then the Mentor should see a "Registration Pending Approval" message & You can access Mentee account for the meantime message
And the Mentor should be redirected to the Login page

### PR DESCRIPTION
**Pull request by ChugxScript**
# Ticket: https://github.com/Angular-PH-X-GuroKonekt-PH/gurokonekt-monorepo/issues/66

### Changes

* Refactored **mentor registration** with improved validation and payload handling.
* Implemented **file uploads** to Supabase bucket with metadata saved to `document_attachments`.
* Excluded **passwords** from API responses and centralized user/mentor select fields in `UtilsService`.
* Fixed type issues (`Express.Multer.File`) and optional field validation for smoother TypeScript integration.
* Handled **Supabase RLS** for uploads using Admin client before user authentication.

Postman if needed: [Register Mentor](https://andrew-7391189.postman.co/workspace/Andrew's-Workspace~9680506d-fc96-428e-83aa-fdde9d80949d/request/45991096-8b706746-d705-4c13-8b8c-d4d50766cae4?action=share&creator=45991096&ctx=documentation)

### CODE REVIEW

File: apps/api/src/app/auth/auth.controller.ts [hunk 1]
```diff
@@ -36,10 +47,35 @@ export class AuthController {
   }
 
   @Post('register-mentor')
+  @ApiConsumes('multipart/form-data')
   @ApiOperation({ summary: 'Register a new mentor' })
   @ApiResponse({ status: 200, description: 'Mentor created successfully', type: AsyncReturnDto })
-  async registerMentor(@Body() input: RegisterMentorDto) {
-    return this.authService.registerMentor(input);
+  @UseInterceptors(
+    FilesInterceptor('files', 5, {
```
Comment (SeijiV13) [inline apps/api/src/app/auth/auth.controller.ts]: FileInterceptors can be separated

File: apps/api/src/app/auth/auth.service.ts [hunk 2]
```diff
@@ -201,6 +260,7 @@ export class AuthService {
         console.error(error);
```
Comment (SeijiV13) [inline apps/api/src/app/auth/auth.service.ts]: remove the conbsole error lets add a logger, monitoring in the next steps

File: apps/api/src/app/auth/auth.service.ts [hunk 3]
```diff
@@ -695,4 +804,91 @@ export class AuthService {
     }
     return sanitized;
   }
+
+  private validateMentorFields(dto: RegisterMentorDto, files: Express.Multer.File[]): {
```
Comment (SeijiV13) [inline apps/api/src/app/auth/auth.service.ts]: can be separatied into a file of validations, also spearate the regex into another file maybe an enum because we can reuse it

File: apps/api/src/app/auth/auth.service.ts [hunk 4]
```diff
@@ -218,46 +278,95 @@ export class AuthService {
...
         data: {
-          auth: data,
-          user: transaction.user,
-          profile: transaction.profile
+          session: data.session,
+          user: transaction.profile
         }
       }
     } catch (error) {
       console.error(error);
```
Comment (SeijiV13) [inline apps/api/src/app/auth/auth.service.ts]: remove console

File: apps/api/src/app/auth/auth.service.ts (hunk 3 above)
Comment (SeijiV13) [reply apps/api/src/app/auth/auth.service.ts]: also Nest has a validation using Decoarators, i would say thats a cleaer approach

Comment (SeijiV13) [reply apps/api/src/app/auth/auth.service.ts]: https://docs.nestjs.com/techniques/validation

File: apps/api/src/app/auth/auth.controller.ts (hunk 1 above)
Comment (ChugxScript) [reply apps/api/src/app/auth/auth.controller.ts]: Commit: https://github.com/Angular-PH-X-GuroKonekt-PH/gurokonekt-monorepo/pull/100/commits/c76aa2f78ca99ef2fee813f4c71e406f3bea495d

File: apps/api/src/app/auth/auth.service.ts (hunk 2 above)
Comment (ChugxScript) [reply apps/api/src/app/auth/auth.service.ts]: Commit: https://github.com/Angular-PH-X-GuroKonekt-PH/gurokonekt-monorepo/pull/100/commits/991f50195ebbfee8dc726c4835bc43fbc2a8eb7d

File: apps/api/src/app/auth/auth.service.ts (hunk 4 above)
Comment (ChugxScript) [reply apps/api/src/app/auth/auth.service.ts]: Commit: https://github.com/Angular-PH-X-GuroKonekt-PH/gurokonekt-monorepo/pull/100/commits/991f50195ebbfee8dc726c4835bc43fbc2a8eb7d

File: apps/api/src/app/auth/auth.service.ts (hunk 3 above)
Comment (ChugxScript) [reply apps/api/src/app/auth/auth.service.ts]: Commit: https://github.com/Angular-PH-X-GuroKonekt-PH/gurokonekt-monorepo/pull/100/commits/2f13229516a7cae84ab375acad5b2fb9c783a58a

**Review by SeijiV13 — APPROVED** [review]
